server:
  port: 8090

spring:
  mail:
    host: smtp.163.com
    username: 18356064622@163.com
    password: ACVCOFQLBCEEHOEVXA
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true